CREATE DATABASE [QuanLyCuaHangGiay]
GO

USE [QuanLyCuaHangGiay]
GO

CREATE TABLE dbo.QUYEN (
    MaQuyen nvarchar(50) NOT NULL,
    TenQuyen nvarchar(100) NOT NULL,
    QL_BanHang int NULL CONSTRAINT DF_QUYEN_QL_BanHang DEFAULT (0),
    QL_KhachHang int NULL CONSTRAINT DF_QUYEN_QL_KhachHang DEFAULT (0),
    QL_SanPham int NULL CONSTRAINT DF_QUYEN_QL_SanPham DEFAULT (0),
    QL_NhapHang int NULL CONSTRAINT DF_QUYEN_QL_NhapHang DEFAULT (0),
    QL_NhanVien int NULL CONSTRAINT DF_QUYEN_QL_NhanVien DEFAULT (0),
    QL_ThongKe int NULL CONSTRAINT DF_QUYEN_QL_ThongKe DEFAULT (0),
    CONSTRAINT PK_QUYEN PRIMARY KEY CLUSTERED (MaQuyen)
)
GO

CREATE TABLE dbo.NHAN_VIEN (
    MaNV nvarchar(50) NOT NULL,
    Ho nvarchar(100) NULL,
    Ten nvarchar(50) NULL,
    MaQuyen nvarchar(50) NOT NULL,
    TaiKhoan nvarchar(50) NOT NULL,
    MatKhau nvarchar(100) NOT NULL,
    Luong decimal(18, 2) NULL,
    TrangThai int NULL CONSTRAINT DF_NHAN_VIEN_TrangThai DEFAULT (1),
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY CLUSTERED (MaNV),
    CONSTRAINT FK_NHAN_VIEN_QUYEN FOREIGN KEY (MaQuyen) REFERENCES dbo.QUYEN (MaQuyen)
)
GO

CREATE TABLE dbo.KHACH_HANG (
    MaKH nvarchar(50) NOT NULL,
    TenKH nvarchar(255) NOT NULL,
    SDT nvarchar(15) NULL,
    DiaChi nvarchar(255) NULL,
    DiemTichLuy int NULL CONSTRAINT DF_KHACH_HANG_DiemTichLuy DEFAULT (0),
    TrangThai int NOT NULL CONSTRAINT DF_KHACH_HANG_TrangThai DEFAULT (1),
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY CLUSTERED (MaKH)
)
GO

CREATE TABLE dbo.NHA_CUNG_CAP (
    MaNCC nvarchar(50) NOT NULL,
    TenNCC nvarchar(255) NOT NULL,
    SDT nvarchar(15) NULL,
    DiaChi nvarchar(255) NULL,
    TrangThai int NULL CONSTRAINT DF_NHA_CUNG_CAP_TrangThai DEFAULT (1),
    CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY CLUSTERED (MaNCC)
)
GO

CREATE TABLE dbo.VOUCHER (
    MaVoucher nvarchar(50) NOT NULL,
    TenVoucher nvarchar(255) NULL,
    PhanTramGiam int NULL,
    SoTienGiam decimal(18, 2) NULL,
    GiamToiDa decimal(18, 2) NULL,
    DieuKienApDung decimal(18, 2) NULL,
    NgayBatDau datetime NULL,
    NgayKetThuc datetime NULL,
    SoLuong int NULL,
    TrangThai int NULL CONSTRAINT DF_VOUCHER_TrangThai DEFAULT (1),
    CONSTRAINT PK_VOUCHER PRIMARY KEY CLUSTERED (MaVoucher)
)
GO

CREATE TABLE dbo.SAN_PHAM (
    MaSP nvarchar(50) NOT NULL,
    TenSP nvarchar(255) NOT NULL,
    LoaiSP nvarchar(100) NULL,
    DonViTinh nvarchar(50) NULL,
    SoLuong int NULL CONSTRAINT DF_SAN_PHAM_SoLuong DEFAULT (0),
    DonGia decimal(18, 2) NULL CONSTRAINT DF_SAN_PHAM_DonGia DEFAULT (0),
    PhanTramLoiNhuan decimal(5, 2) NULL CONSTRAINT DF_SAN_PHAM_PhanTramLoiNhuan DEFAULT (20),
    MauSac nvarchar(50) NULL,
    Size nvarchar(10) NULL,
    ChatLieu nvarchar(100) NULL,
    ThuongHieu nvarchar(100) NULL,
    NuocSanXuat nvarchar(100) NULL,
    NgaySanXuat datetime NULL,
    MoTa nvarchar(max) NULL,
    HinhAnh nvarchar(max) NULL,
    MaNCC nvarchar(50) NULL,
    TrangThai int NULL CONSTRAINT DF_SAN_PHAM_TrangThai DEFAULT (1),
    CONSTRAINT PK_SAN_PHAM PRIMARY KEY CLUSTERED (MaSP),
    CONSTRAINT FK_SAN_PHAM_NHA_CUNG_CAP FOREIGN KEY (MaNCC) REFERENCES dbo.NHA_CUNG_CAP (MaNCC)
)
GO

CREATE TABLE dbo.PHIEU_NHAP (
    MaPN nvarchar(50) NOT NULL,
    MaNV nvarchar(50) NOT NULL,
    MaNCC nvarchar(50) NOT NULL,
    NgayNhap datetime NULL CONSTRAINT DF_PHIEU_NHAP_NgayNhap DEFAULT (GETDATE()),
    TongSoMatHang int NULL CONSTRAINT DF_PHIEU_NHAP_TongSoMatHang DEFAULT (0),
    TongTien decimal(18, 2) NULL CONSTRAINT DF_PHIEU_NHAP_TongTien DEFAULT (0),
    CONSTRAINT PK_PHIEU_NHAP PRIMARY KEY CLUSTERED (MaPN),
    CONSTRAINT FK_PHIEU_NHAP_NHA_CUNG_CAP FOREIGN KEY (MaNCC) REFERENCES dbo.NHA_CUNG_CAP (MaNCC),
    CONSTRAINT FK_PHIEU_NHAP_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV)
)
GO

CREATE TABLE dbo.HOA_DON (
    MaHD nvarchar(50) NOT NULL,
    MaNV nvarchar(50) NOT NULL,
    MaKH nvarchar(50) NULL,
    MaVoucher nvarchar(50) NULL,
    NgayLap datetime NULL CONSTRAINT DF_HOA_DON_NgayLap DEFAULT (GETDATE()),
    TongTien decimal(18, 2) NULL CONSTRAINT DF_HOA_DON_TongTien DEFAULT (0),
    CONSTRAINT PK_HOA_DON PRIMARY KEY CLUSTERED (MaHD),
    CONSTRAINT FK_HOA_DON_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG (MaKH),
    CONSTRAINT FK_HOA_DON_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT FK_HOA_DON_VOUCHER FOREIGN KEY (MaVoucher) REFERENCES dbo.VOUCHER (MaVoucher)
)
GO

CREATE TABLE dbo.CHI_TIET_PHIEU_NHAP (
    MaPN nvarchar(50) NOT NULL,
    MaSP nvarchar(50) NOT NULL,
    SoLuong int NULL,
    GiaNhap decimal(18, 2) NULL,
    CONSTRAINT PK_CHI_TIET_PHIEU_NHAP PRIMARY KEY CLUSTERED (MaPN, MaSP),
    CONSTRAINT FK_CHI_TIET_PHIEU_NHAP_PHIEU_NHAP FOREIGN KEY (MaPN) REFERENCES dbo.PHIEU_NHAP (MaPN),
    CONSTRAINT FK_CHI_TIET_PHIEU_NHAP_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP),
    CONSTRAINT CK_CHI_TIET_PHIEU_NHAP_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_CHI_TIET_PHIEU_NHAP_GiaNhap CHECK (GiaNhap >= 0)
)
GO

CREATE TABLE dbo.CHI_TIET_HOA_DON (
    MaHD nvarchar(50) NOT NULL,
    MaSP nvarchar(50) NOT NULL,
    SoLuong int NULL,
    DonGia decimal(18, 2) NULL,
    CONSTRAINT PK_CHI_TIET_HOA_DON PRIMARY KEY CLUSTERED (MaHD, MaSP),
    CONSTRAINT FK_CHI_TIET_HOA_DON_HOA_DON FOREIGN KEY (MaHD) REFERENCES dbo.HOA_DON (MaHD),
    CONSTRAINT FK_CHI_TIET_HOA_DON_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP),
    CONSTRAINT CK_CHI_TIET_HOA_DON_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_CHI_TIET_HOA_DON_DonGia CHECK (DonGia >= 0)
)
GO

CREATE TABLE dbo.DOI_TRA (
    MaDT nvarchar(50) NOT NULL,
    MaHD nvarchar(50) NOT NULL,
    MaNV nvarchar(50) NOT NULL,
    MaSP nvarchar(50) NOT NULL,
    NgayDoiTra datetime NULL CONSTRAINT DF_DOI_TRA_NgayDoiTra DEFAULT (GETDATE()),
    SoLuong int NULL,
    TongTienHoan decimal(18, 2) NULL,
    LyDo nvarchar(255) NULL,
    TinhTrang nvarchar(100) NULL,
    CONSTRAINT PK_DOI_TRA PRIMARY KEY CLUSTERED (MaDT),
    CONSTRAINT FK_DOI_TRA_HOA_DON FOREIGN KEY (MaHD) REFERENCES dbo.HOA_DON (MaHD),
    CONSTRAINT FK_DOI_TRA_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT FK_DOI_TRA_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP)
)
GO

CREATE TABLE dbo.PHIEU_BAO_HANH (
    MaPBH nvarchar(50) NOT NULL,
    MaHD nvarchar(50) NOT NULL,
    MaSP nvarchar(50) NOT NULL,
    MaKH nvarchar(50) NOT NULL,
    NgayNhan datetime NULL,
    NgayTraDuKien datetime NULL,
    LoiCanBaoHanh nvarchar(max) NULL,
    ChiPhiPhatSinh decimal(18, 2) NULL CONSTRAINT DF_PHIEU_BAO_HANH_ChiPhiPhatSinh DEFAULT (0),
    TrangThai int NULL CONSTRAINT DF_PHIEU_BAO_HANH_TrangThai DEFAULT (0),
    CONSTRAINT PK_PHIEU_BAO_HANH PRIMARY KEY CLUSTERED (MaPBH),
    CONSTRAINT FK_PHIEU_BAO_HANH_HOA_DON FOREIGN KEY (MaHD) REFERENCES dbo.HOA_DON (MaHD),
    CONSTRAINT FK_PHIEU_BAO_HANH_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG (MaKH),
    CONSTRAINT FK_PHIEU_BAO_HANH_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP)
)
GO

CREATE TABLE dbo.PHIEU_TRA_NCC (
    MaPT nvarchar(50) NOT NULL,
    MaPN nvarchar(50) NOT NULL,
    MaNV nvarchar(50) NOT NULL,
    MaNCC nvarchar(50) NOT NULL,
    NgayTao date NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_NgayTao DEFAULT (CONVERT(date, GETDATE())),
    TongSoMatHang int NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_TongSoMatHang DEFAULT (0),
    TongTien decimal(18, 2) NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_TongTien DEFAULT (0),
    LyDo nvarchar(255) NULL,
    TrangThai nvarchar(30) NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_TrangThai DEFAULT (N'Đang duyệt'),
    NgayXuLy date NULL,
    NguoiXuLy nvarchar(50) NULL,
    CONSTRAINT PK_PHIEU_TRA_NCC PRIMARY KEY CLUSTERED (MaPT),
    CONSTRAINT FK_PHIEU_TRA_NCC_PHIEU_NHAP FOREIGN KEY (MaPN) REFERENCES dbo.PHIEU_NHAP (MaPN),
    CONSTRAINT FK_PHIEU_TRA_NCC_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT FK_PHIEU_TRA_NCC_NHA_CUNG_CAP FOREIGN KEY (MaNCC) REFERENCES dbo.NHA_CUNG_CAP (MaNCC)
)
GO

CREATE TABLE dbo.CHI_TIET_TRA_NCC (
    MaPT nvarchar(50) NOT NULL,
    MaSP nvarchar(50) NOT NULL,
    SoLuong int NOT NULL,
    GiaNhap decimal(18, 2) NOT NULL,
    CONSTRAINT PK_CHI_TIET_TRA_NCC PRIMARY KEY CLUSTERED (MaPT, MaSP),
    CONSTRAINT FK_CHI_TIET_TRA_NCC_PHIEU_TRA FOREIGN KEY (MaPT) REFERENCES dbo.PHIEU_TRA_NCC (MaPT),
    CONSTRAINT FK_CHI_TIET_TRA_NCC_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP),
    CONSTRAINT CK_CHI_TIET_TRA_NCC_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_CHI_TIET_TRA_NCC_GiaNhap CHECK (GiaNhap >= 0)
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_SAN_PHAM_BienThe
    ON dbo.SAN_PHAM (TenSP, ThuongHieu, MauSac, Size)
    WHERE MauSac IS NOT NULL AND Size IS NOT NULL
GO
