IF COL_LENGTH('dbo.SAN_PHAM', 'MaNCC') IS NULL
BEGIN
    ALTER TABLE dbo.SAN_PHAM ADD MaNCC nvarchar(50) NULL;
    ALTER TABLE dbo.SAN_PHAM
        ADD CONSTRAINT FK_SAN_PHAM_NHA_CUNG_CAP
        FOREIGN KEY (MaNCC) REFERENCES dbo.NHA_CUNG_CAP(MaNCC);
END;