USE QuanLyCuaHangGiay;
GO

IF OBJECT_ID(N'dbo.PHIEU_TRA_NCC', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PHIEU_TRA_NCC(
        MaPT nvarchar(50) NOT NULL,
        MaPN nvarchar(50) NOT NULL,
        MaNV nvarchar(50) NOT NULL,
        MaNCC nvarchar(50) NOT NULL,
        NgayTao date NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_NgayTao DEFAULT (CONVERT(date, GETDATE())),
        TongSoMatHang int NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_TongSoMatHang DEFAULT (0),
        TongTien decimal(18, 2) NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_TongTien DEFAULT (0),
        LyDo nvarchar(255) NULL,
        TrangThai nvarchar(30) NOT NULL CONSTRAINT DF_PHIEU_TRA_NCC_TrangThai DEFAULT (N'Đang duyệt'),
        NgayXuLy date NULL,
        NguoiXuLy nvarchar(50) NULL,
        CONSTRAINT PK_PHIEU_TRA_NCC PRIMARY KEY (MaPT),
        CONSTRAINT FK_PHIEU_TRA_NCC_PHIEU_NHAP FOREIGN KEY (MaPN) REFERENCES dbo.PHIEU_NHAP(MaPN),
        CONSTRAINT FK_PHIEU_TRA_NCC_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN(MaNV),
        CONSTRAINT FK_PHIEU_TRA_NCC_NHA_CUNG_CAP FOREIGN KEY (MaNCC) REFERENCES dbo.NHA_CUNG_CAP(MaNCC)
    );
END;
GO

IF OBJECT_ID(N'dbo.CHI_TIET_TRA_NCC', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHI_TIET_TRA_NCC(
        MaPT nvarchar(50) NOT NULL,
        MaSP nvarchar(50) NOT NULL,
        SoLuong int NOT NULL,
        GiaNhap decimal(18, 2) NOT NULL,
        CONSTRAINT PK_CHI_TIET_TRA_NCC PRIMARY KEY (MaPT, MaSP),
        CONSTRAINT FK_CHI_TIET_TRA_NCC_PHIEU_TRA FOREIGN KEY (MaPT) REFERENCES dbo.PHIEU_TRA_NCC(MaPT),
        CONSTRAINT FK_CHI_TIET_TRA_NCC_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM(MaSP),
        CONSTRAINT CK_CHI_TIET_TRA_NCC_SoLuong CHECK (SoLuong > 0),
        CONSTRAINT CK_CHI_TIET_TRA_NCC_GiaNhap CHECK (GiaNhap >= 0)
    );
END;
GO
